### ISSUE TITLE
I Need Help :  rjrouquette

### ISSUE THREAD

**Issue by DheerajT4630** [rjrouquette/rgb_matrix_udp#15]
Hi rjrouquette ,

I need your help please.
I am correctly working on RGB LED Matrix Displays using Raspberry pi cm4. now i can run sample example code from hzeller/rpi-rgb-led-matrix and my display working properly. 
i need your help how to use your rgb_matrix_udp ?. can i use your rgb_matrix_udp with hzeller/rpi-rgb-led-matrix or it's work separately?
please please help.

**Comment by rjrouquette** [comment]
This project is not compatible with `hzeller/rpi-rgb-led-matrix`.  `rgb_matrix_udp` is an alternative to `hzeller/rpi-rgb-led-matrix` that uses the DPI interface in combination with an external logic board to drive the LED panels.  The DPI interface is a raster display output with a synchronous parallel data bus.  Aside from the physical interface, this code is also designed for driving multiple rapsberry pi's from a single broadcast server.

This code is not intended for beginners and requires familiarity with UDP/IP, UNIX domain sockets, raster displays, network time synchronization (chrony), low-level microcontroller code, and discrete digital logic.

Hackaday link for this project: https://hackaday.io/project/170109-improved-raspberry-pi-rgb-matrix-driver
