### ISSUE TITLE
Image/video quality 

### ISSUE THREAD

**Issue by arahasya** [rjrouquette/rgb_matrix_udp#6]
Hi again Robert,
I am now using your driver to display photos and videos. When I compare the same content with rpi-rgb-led-matrix using active adapter, the later showed better picture quality. The difference isn't big but still visible.

I have set the clock at 19200000 and tried different refresh rates from 275 (max) to 80. At 80 the colour leakages reduce a bit but still the overall contrast seems better with rpi-rgb-led-matrix
It is hard to capture the difference with phone camera but I have tried. Please ignore the colour patch when I am using your adapter with 4 chains. It is display problem. With other library there are only 3 chains so that patch is not used.

[comparison.zip](https://github.com/rjrouquette/rgb_matrix_udp/files/4832868/comparison.zip)

**Comment by rjrouquette** [comment]
So fwiw, the "refresh rate" in the DPI config line has no effect on the panel scan rate or the hardware PWM.  You can try further reducing the pixel clock to 9.6 MHz (9600000) and see if that helps.

I do agree that your top chain appears to have ESD damage judging by the bright line artifacts and the discoloration.

**Comment by rjrouquette** [comment]
I have a panel with similar ESD damage.  I'm currently writing a utility to display test patterns so I can determine if your color issues are a software issue or a hardware issue.
![497F713E-EF69-4C55-B192-3DA767A0EC50](https://user-images.githubusercontent.com/20068421/85798231-bd2ecd00-b702-11ea-96a6-a220298b1985.jpeg)

**Comment by rjrouquette** [comment]
So it looks like your color issue is because you are using createPwmLutLinear() which is only for hardware debugging purposes.  You need to use createPwmLutCie1931() to make the color correct.  I've pushed the change, and I'll provide comparison images in a moment.

**Comment by rjrouquette** [comment]
With Linear PWM:
![419970BE-758A-43F6-B0DF-17E4BC51512C](https://user-images.githubusercontent.com/20068421/85803301-7219b780-b70c-11ea-9f0b-57f6aa363ac2.jpeg)


With CIE1931:
![F908A795-D3EF-403B-B3A3-56ADBF5E6DD3](https://user-images.githubusercontent.com/20068421/85802952-a9d42f80-b70b-11ea-9b0c-0f3512e45d83.jpeg)

It's hard to tell from the images, but the linear PWM creates washed-out gradients.

**Comment by arahasya** [comment]
Thanks. I will try out this soon on my display. Facing some technical issues right now
