### ISSUE TITLE
Weird flashing noise on display

### ISSUE THREAD

**Issue by arahasya** [rjrouquette/rgb_matrix_udp#9]
I connected the display after a while and I am seeing this weird pattern which is flashing after connecting the HUB75 cables

It is flashing even when the application is not running

[flash.mp4.zip](https://github.com/rjrouquette/rgb_matrix_udp/files/4936675/flash.mp4.zip)

/boot/config.txt

dpi_timings=288 0 0 8 0 177 0 0 1 0 0 0 0 460 0 19200000 3

framebuffer_width=288
framebuffer_height=177
framebuffer_depth=32
framebuffer_ignore_alpha=1
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0

gpu_mem=64

**Comment by rjrouquette** [comment]
You might want to verify that the pi 5V supply is stable.  I've seen that before on mine that if the 5V supply voltage is too low.  The kernel  prints messages to the console whenever the supply browns-out and that causes the flickering.  If it persists you can try disabling the getty@tty1.service, but it's usually kernel console messages that cause the flickering.  You can also try pulling in my change that increases the bit-blit rate.

**Comment by arahasya** [comment]
Yes. It was problem with power supply. Thanks! Have you received my e-mail for a support request?

**Comment by arahasya** [comment]
There?
